set_property IOSTANDARD LVCMOS33 [get_ports main_clk]
set_property IOSTANDARD LVCMOS33 [get_ports pll_reset]
set_property IOSTANDARD LVCMOS33 [get_ports core_reset]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_out[0]}]

set_property PACKAGE_PIN Y9 [get_ports main_clk]
set_property PACKAGE_PIN F22 [get_ports pll_reset]
set_property PACKAGE_PIN G22 [get_ports core_reset]
set_property PACKAGE_PIN U14 [get_ports {dac_out[7]}]
set_property PACKAGE_PIN U19 [get_ports {dac_out[6]}]
set_property PACKAGE_PIN W22 [get_ports {dac_out[5]}]
set_property PACKAGE_PIN V22 [get_ports {dac_out[4]}]
set_property PACKAGE_PIN U21 [get_ports {dac_out[3]}]
set_property PACKAGE_PIN U22 [get_ports {dac_out[2]}]
set_property PACKAGE_PIN T21 [get_ports {dac_out[1]}]
set_property PACKAGE_PIN T22 [get_ports {dac_out[0]}]

create_clock -period 30.303 -name primary_clk -waveform {0.000 15.000} -add [get_ports main_clk]
